# [module.hugoVersion]
# min = "0.111.3"

[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hbstack/header"

[params.hb.announcement_bar]
interval = 5000
expand_stall_threshold = 500

[params.hugopress.modules.hb-announcement-bar.hooks.hb-header-nav-before]
cacheable = true
weight = 1
