name: Playwright Tests
on:
  push:
jobs:
  test:
    strategy:
      matrix:
        version:
          - latest
        case: [default]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Setup caches
        uses: actions/cache@v4
        with:
          path: /home/runner/.cache/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ matrix.version }}
          extended: true
      - name: Install dependencies
        working-directory: tests/${{ matrix.case }}
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: tests/${{ matrix.case }}
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: tests/${{ matrix.case }}
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: tests/${{ matrix.case }}/playwright-report/
          retention-days: 30
